import { createMotionUiAdapter } from "./app-adapter.js";
import { assertSafeCanonicalWorkspaceIds, escapeAttribute } from "./canonical-security.js";
import { renderBlockTypeSelect } from "./block-presentation.js";
import { confirmBrowserEdit } from "./browser-edit-confirmation.js"; import { createNativeCommandController } from "./command-router.js";
import { createEditRecoveryController } from "./edit-recovery.js";
import { createOperationCoordinator } from "./operation-coordinator.js"; import { createAttachmentIngestion } from "./attachment-ingestion.js";
import { buildBrowserSearchHits, normalizeSearchHits, resolveSearchTarget, searchStatus } from "./search-recovery.js"; import { buildInternalUrl } from "./internal-links.js";
import { multilinePasteCommands } from "./markdown-paste.js";
import { normalizeWorkspaceV1 } from "./workspace-v1.js";

const adapter = createMotionUiAdapter();
const $ = selector => document.querySelector(selector);
const uid = () => crypto.randomUUID();
const now = () => new Date().toISOString();
const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" })[char]);
const PROPERTY_TYPES = ["text","number","checkbox","select","multi-select","status","date","url","email","phone"];
const PROPERTY_LABELS = { title:"Title", text:"Text", "plain-text":"Text", number:"Number", checkbox:"Checkbox", select:"Select", "multi-select":"Multi-select", status:"Status", date:"Date", url:"URL", email:"Email", phone:"Phone" };
const BLOCK_TYPES = ["paragraph","heading-1","heading-2","heading-3","bulleted-list","numbered-list","task","quote","code","divider"];
const BLOCK_LABELS = { paragraph:"Text", "heading-1":"Heading 1", "heading-2":"Heading 2", "heading-3":"Heading 3", "bulleted-list":"Bulleted list", "numbered-list":"Numbered list", task:"Task", quote:"Quote", code:"Code", divider:"Divider" };
const EMPTY = { schemaVersion:2, workspace:null, revision:0, activePageId:null, expandedPageIds:[] };
let state = migrateLoaded(await adapter.load()); const nativeCommands=adapter.kind==="tauri"?createNativeCommandController({execute:(type,payload)=>adapter.execute(type,payload),currentRevision:()=>state.revision,confirm:(confirmed,revision)=>confirmNativeSnapshot(confirmed,revision)}):null;
let history = [], future = [], navigation = [], saveQueue = Promise.resolve(), editing = null, editTimer = null, activeEditMeta = null, searchRequest = 0, currentSearchHits = new Map();

function canonicalWorkspace(value) { if (value !== null && value !== undefined) assertSafeCanonicalWorkspaceIds(value); return value; }
function migrateLoaded(value) {
  if (value?.schemaVersion === 2) return { ...EMPTY, ...value, workspace:canonicalWorkspace(value.workspace), expandedPageIds:value.expandedPageIds ?? [] };
  const legacy = normalizeWorkspaceV1(value), stamp = now(), databases = [], pages = [];
  for (const source of legacy.pages) {
    const page = { id:source.id, parentId:source.parentId, title:source.title, blocks:(source.blocks ?? []).map(block => ({ id:block.id, type:({ heading1:"heading-1",heading2:"heading-2",heading3:"heading-3",bullet:"bulleted-list",number:"numbered-list" })[block.type] ?? block.type, text:block.text, children:[], checked:block.checked, references:(block.links ?? []).filter(link => link.pageId).map(link => ({ pageId:link.pageId })) })), createdAt:stamp, updatedAt:stamp, deletedAt:source.deleted ? stamp : undefined, favourite:false };
    pages.push(page);
    if (source.type === "database") {
      const databaseId = uid(), properties = source.columns.map((column,index) => ({ id:column.id, name:column.name, type:index === 0 ? "title" : "text" }));
      const recordPageIds = source.rows.map(row => { const record = { id:row.id, parentId:source.id, title:String(row.values[properties[0]?.id] ?? "Untitled"), blocks:[], createdAt:stamp, updatedAt:stamp, collectionId:databaseId, properties:{ ...row.values } }; delete record.properties[properties[0]?.id]; pages.push(record); return record.id; });
      databases.push({ id:databaseId, pageId:source.id, name:source.title, properties, rows:[], recordPageIds, views:[{ id:uid(), collectionId:databaseId, name:"Table", type:"table", visiblePropertyIds:properties.map(p=>p.id), propertyOrder:properties.map(p=>p.id), columnWidths:{} }] });
    }
  }
  return { schemaVersion:2, workspace:{ schemaVersion:2,id:uid(),name:"Motion Workspace",pages,databases,attachments:[],linkIndex:[],createdAt:stamp,updatedAt:stamp },revision:1,activePageId:legacy.activePageId,expandedPageIds:[] };
}
const workspace = () => state.workspace;
function confirmNativeSnapshot(confirmed,revision){if(revision<=state.revision)return false;state.workspace=canonicalWorkspace(confirmed);state.revision=revision;return true;}
const pageById = id => workspace()?.pages.find(page => page.id === id);
const activePage = () => pageById(state.activePageId);
const databaseForPage = page => workspace()?.databases.find(database => database.pageId === page?.id || database.id === page?.collectionId);
const visiblePages = () => workspace()?.pages.filter(page => !page.deletedAt) ?? [];
const childrenOf = parentId => visiblePages().filter(page => page.parentId === parentId && !page.collectionId);
const snapshot = () => JSON.stringify(state);
function checkpoint() { history.push(snapshot()); if (history.length > 80) history.shift(); future=[]; }
async function saveLocal() { if (adapter.kind !== "browser-development") return; saveQueue=saveQueue.catch(()=>{}).then(()=>adapter.save(structuredClone(state))); await saveQueue; }
async function saveUi() { await adapter.saveUi({ workspaceId:workspace()?.id, activePageId:state.activePageId, expandedPageIds:state.expandedPageIds }); if (adapter.kind === "browser-development") await saveLocal(); }
async function commit(type,payload,localMutation) {
  $("#saveState").textContent="Saving…";
  try {
    if (adapter.kind === "tauri") await nativeCommands.execute(type,payload);
    else { localMutation(); state.workspace.updatedAt=now(); state.revision++; await saveLocal(); }
    $("#saveState").textContent=adapter.kind === "tauri" ? "Saved to Motion" : "Saved in browser (development mode)";
  } catch (error) { $("#saveState").textContent="Save failed"; alert("Motion could not save this change."); throw error; }
}
async function confirmCanonicalEdit({candidate}) {
  if(adapter.kind==="tauri"){
    await nativeCommands.execute(candidate.type,candidate.payload);

  }else{
    const confirmed=await confirmBrowserEdit(state,candidate,document=>{saveQueue=saveQueue.catch(()=>{}).then(()=>adapter.save(document));return saveQueue;},now);state=migrateLoaded(confirmed);
  }
}

function editTarget(target){
  if(!target)return null;
  if(target.kind==="page-title")return $("#pageTitle");
  if(target.kind==="block-text")return findByDataValue("[data-block]","block",target.blockId);
  if(target.kind==="block-type")return findByDataValue("[data-block-type]","blockType",target.blockId);
  if(target.kind==="task")return findByDataValue("[data-task]","task",target.blockId);
  if(target.kind==="record-property")return [...document.querySelectorAll("[data-property]")].find(element=>element.dataset.property===target.propertyId&&(element.dataset.record??state.activePageId)===target.pageId);
  if(target.kind==="view-width")return findByDataValue("[data-column-width]","columnWidth",target.propertyId);
  return null;
}

function restoreRejectedEditTarget(target){
  const element=editTarget(target);if(!element)return;
  const page=pageById(target.pageId);
  if(target.kind==="page-title")element.value=page?.title??"";
  else if(target.kind==="block-text")element.textContent=page?.blocks.find(block=>block.id===target.blockId)?.text??"";
  else if(target.kind==="block-type")element.value=page?.blocks.find(block=>block.id===target.blockId)?.type??"paragraph";
  else if(target.kind==="task")element.checked=Boolean(page?.blocks.find(block=>block.id===target.blockId)?.checked);
  else if(target.kind==="view-width"){const database=databaseForPage(page),property=database?.properties.find(item=>item.id===target.propertyId);element.value=database?.views[0].columnWidths?.[target.propertyId]??(property?.type==="title"?280:170);}
  else if(target.kind==="record-property"){
    const property=databaseForPage(page)?.properties.find(item=>item.id===target.propertyId),value=page?.properties?.[target.propertyId];
    if(property?.type==="checkbox")element.checked=Boolean(value);
    else if(property?.type==="multi-select")for(const option of element.options)option.selected=Array.isArray(value)&&value.includes(option.value);
    else element.value=value??"";
  }
}

function markPendingEdit(snapshot){
  document.querySelectorAll('[data-unsaved="true"]').forEach(element=>{element.removeAttribute("data-unsaved");element.removeAttribute("aria-invalid");element.removeAttribute("aria-describedby");});
  if(!snapshot.blocked)return;
  const target=editTarget(snapshot.target);if(!target)return;
  target.dataset.unsaved="true";target.setAttribute("aria-describedby",snapshot.status==="failed"?"editRecoveryMessage":"saveState");
  if(snapshot.status==="failed")target.setAttribute("aria-invalid","true");
}

function syncEditRecovery(snapshot){
  const recovery=$("#editRecovery"),saveState=$("#saveState"),failed=snapshot.status==="failed";
  clearTimeout(editTimer);editTimer=null;markPendingEdit(snapshot);
  if(!snapshot.blocked){
    recovery.hidden=true;saveState.className="save-state";
    if(snapshot.saved){saveState.textContent=adapter.kind==="tauri"?"Saved to Motion":"Saved in browser (development mode)";const meta=activeEditMeta;if(meta?.rerender)render();requestAnimationFrame(()=>editTarget(meta?.target)?.focus());}
    return;
  }
  saveState.className=`save-state ${failed?"unsaved":"saving"}`;
  saveState.textContent=failed?"Unsaved change — action required":`${snapshot.label} has unsaved changes. Saving…`;
  recovery.hidden=!failed;
  if(failed){$("#editRecoveryMessage").textContent=`${snapshot.label} could not be saved.`;requestAnimationFrame(()=>editTarget(snapshot.target)?.focus());}
  else if(snapshot.status==="editing")editTimer=setTimeout(()=>void editRecovery.commit(),180);
}

const operationCoordinator=createOperationCoordinator();
const editRecovery=createEditRecoveryController({confirm:confirmCanonicalEdit,onChange:syncEditRecovery,acquireEdit:operationCoordinator.beginEdit,releaseEdit:operationCoordinator.endEdit});

function queueCanonicalEdit({key,label,candidate,target,rerender=false}){
  if(editRecovery.update({key,label,candidate,target})){activeEditMeta={target,rerender};return true;}
  restoreRejectedEditTarget(target);
  const pending=editRecovery.snapshot();
  if(pending.blocked){syncEditRecovery(pending);$("#editRecoveryMessage").textContent="Resolve the unsaved edit before editing other content.";requestAnimationFrame(()=>editTarget(pending.target)?.focus());}
  else{$("#saveState").textContent=`${operationCoordinator.snapshot().canonicalOperation} in progress — edit not applied.`;requestAnimationFrame(()=>editTarget(target)?.focus());}
  return false;
}
function requireResolvedEdit(action){
  const pending=editRecovery.snapshot();if(!pending.blocked)return true;
  clearTimeout(editTimer);editTimer=null;$("#editRecovery").hidden=false;$("#editRecoveryMessage").textContent=`Retry or discard the unsaved edit before ${action}.`;$("#saveState").className="save-state unsaved";$("#saveState").textContent="Unsaved change — action required";markPendingEdit({...pending,status:"failed"});requestAnimationFrame(()=>$("#retryEdit").focus());return false;
}
async function retryPendingEdit(){return editRecovery.retry();}
function discardPendingEdit(){const discarded=editRecovery.discard();if(!discarded)return false;activeEditMeta=null;render();$("#saveState").textContent=`${discarded.label} unsaved changes discarded.`;requestAnimationFrame(()=>editTarget(discarded.target)?.focus());return true;}
window.addEventListener("beforeunload",event=>{if(!editRecovery.snapshot().blocked)return;event.preventDefault();event.returnValue="";});

async function ensureWorkspace() {
  if (workspace()) return;
  if (adapter.kind === "tauri") await nativeCommands.execute("workspace.create",{name:"Motion Workspace"});
  else { const stamp=now(); state.workspace={schemaVersion:2,id:uid(),name:"Motion Workspace",pages:[],databases:[],attachments:[],linkIndex:[],createdAt:stamp,updatedAt:stamp}; state.revision=1; }
}
function downloadJson(value,fileName){const blob=new Blob([JSON.stringify(value,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=fileName;link.click();URL.revokeObjectURL(url);}
async function runCanonicalOperation(action,operation){const result=await operationCoordinator.runCanonical(action,operation);if(result.started)return result.value;if(editRecovery.snapshot().blocked)requireResolvedEdit(action);return false;}
async function exportWorkspace(){return runCanonicalOperation("exporting",async()=>{const date=new Date().toISOString().slice(0,10);if(adapter.kind==="tauri")downloadJson(await adapter.exportWorkspace(),`motion-canonical-export-${date}.json`);else downloadJson({exportVersion:"motion.workspace/2.0",exportedAt:now(),workspace:state.workspace},`motion-browser-development-${date}.json`);return true;});}
async function sha256(bytes){const digest=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("");}
const attachmentIngestion=createAttachmentIngestion({activePage,authority:()=>({workspaceId:workspace()?.id,pageId:activePage()?.id,revision:state.revision}),runCanonical:runCanonicalOperation,ingest:payload=>adapter.ingestAttachmentBlock(payload),digest:sha256,confirm:result=>{confirmNativeSnapshot(result.workspace,result.revision);render();},status:message=>{$("#saveState").textContent=message;}});
async function createVerifiedBackup(){return runCanonicalOperation("creating a backup",async()=>{const bundle=await adapter.createBackup(),verification=await adapter.verifyBackup(bundle);if(!verification.valid)throw new Error(verification.errors.join("; "));downloadJson(bundle,`motion-verified-backup-${new Date().toISOString().slice(0,10)}.json`);return true;});}
async function restoreVerifiedBackup(file){return runCanonicalOperation("restoring",async()=>{const bundle=JSON.parse(await file.text()),verification=await adapter.verifyBackup(bundle);if(!verification.valid)throw new Error(verification.errors.join("; "));const preview=await adapter.previewBackup(bundle);if(!confirm(`Restore ${preview.workspaceName??"workspace"} with ${preview.pages} pages as a new workspace?`))return false;await adapter.restoreBackup(bundle);state=migrateLoaded(await adapter.load());render();return true;});}
async function restoreWorkspace(file){return runCanonicalOperation("restoring",async()=>{const parsed=JSON.parse(await file.text()),candidate=parsed?.workspace??parsed;if(candidate?.schemaVersion===2&&Array.isArray(candidate.pages)&&Array.isArray(candidate.databases)){if(adapter.kind==="tauri")throw new Error("Use a verified native backup to restore a canonical workspace.");assertSafeCanonicalWorkspaceIds(candidate);const restored={...EMPTY,workspace:structuredClone(candidate),revision:1,activePageId:candidate.pages.find(page=>!page.deletedAt)?.id??null};await adapter.save(structuredClone(restored));state=restored;render();return true;}const legacy=normalizeWorkspaceV1(candidate);if(adapter.kind==="tauri"){const imported=await adapter.importWebV1(legacy);state={...EMPTY,schemaVersion:2,workspace:canonicalWorkspace(imported.workspace),revision:imported.revision,activePageId:imported.activePageId};}else{const restored=migrateLoaded(legacy);await adapter.save(structuredClone(restored));state=restored;}render();return true;});}
function openPage(id,push=true) { if(id!==state.activePageId&&!requireResolvedEdit("leaving this page"))return false;if (push && state.activePageId && state.activePageId !== id) navigation.push(state.activePageId); state.activePageId=id; void saveUi(); render(); $("#sidebar").classList.remove("open"); return true;}
function ancestors(page) { const path=[]; for(let current=page;current;current=pageById(current.parentId)) path.unshift(current); return path; }
function descendants(id) { const result=[]; for(const child of visiblePages().filter(page=>page.parentId===id)){ result.push(child,...descendants(child.id)); } return result; }
function delegatedIdAndDelta(value){const separator=value.lastIndexOf(":");return[value.slice(0,separator),Number(value.slice(separator+1))];}
function rebuildLinks() { if (adapter.kind === "tauri") return; if (!workspace()) return; const links=[]; for(const page of workspace().pages) for(const block of page.blocks ?? []) { const targets=new Set((block.references ?? []).map(ref=>ref.pageId)); for(const match of block.text.matchAll(/\[\[([^\]]+)\]\]/g)){ const target=workspace().pages.find(candidate=>candidate.title.toLowerCase()===match[1].trim().toLowerCase()); if(target) targets.add(target.id); } for(const targetPageId of targets) links.push({sourcePageId:page.id,targetPageId,blockId:block.id}); } workspace().linkIndex=links; }
function refreshReferences(block){const targets=new Set((block.references??[]).map(reference=>reference.pageId));for(const match of block.text.matchAll(/\[\[([^\]]+)\]\]/g)){const target=workspace().pages.find(page=>page.title.toLowerCase()===match[1].trim().toLowerCase());if(target)targets.add(target.id);}block.references=[...targets].map(pageId=>({pageId}));}
function referencesForText(text){const block={text,references:[]};refreshReferences(block);return block.references;}
function selectionTextParts(input){const selection=window.getSelection();if(!selection?.rangeCount)return{prefix:input.textContent??"",suffix:""};const range=selection.getRangeAt(0);if(!input.contains(range.startContainer)||!input.contains(range.endContainer))return{prefix:input.textContent??"",suffix:""};const prefixRange=range.cloneRange(),suffixRange=range.cloneRange();prefixRange.selectNodeContents(input);prefixRange.setEnd(range.startContainer,range.startOffset);suffixRange.selectNodeContents(input);suffixRange.setStart(range.endContainer,range.endOffset);return{prefix:prefixRange.toString(),suffix:suffixRange.toString()};}
function isFileBlock(block){return block.type==="file";}

async function createPage(parentId=null,database=false) {
  checkpoint(); await ensureWorkspace(); const title=database ? "Untitled database" : "Untitled page";
  await commit(database?"database.create":"page.create",{title,parentId},()=>{ const stamp=now(),page={id:uid(),parentId,title,blocks:database?[]:[{id:uid(),type:"paragraph",text:"",children:[]}],createdAt:stamp,updatedAt:stamp,favourite:false}; workspace().pages.push(page); if(database){const dbId=uid(),propertyId=uid(); workspace().databases.push({id:dbId,pageId:page.id,name:title,properties:[{id:propertyId,name:"Name",type:"title"}],rows:[],recordPageIds:[],views:[{id:uid(),collectionId:dbId,name:"Table",type:"table",visiblePropertyIds:[propertyId],propertyOrder:[propertyId],columnWidths:{[propertyId]:280},sorts:[]}]});}});
  const created=[...visiblePages()].reverse().find(page=>page.title===title && page.parentId===parentId); if(created){ state.expandedPageIds=[...new Set([...state.expandedPageIds,...ancestors(created).map(page=>page.id)])]; openPage(created.id); requestAnimationFrame(()=>$("#pageTitle")?.select()); }
}
async function renamePage(page,title) { const old=page.title; await commit("page.rename",{pageId:page.id,title},()=>{page.title=title;page.updatedAt=now();}); if(adapter.kind!=="tauri"){const db=databaseForPage(page);if(db&&db.pageId===page.id)db.name=title;} if(old!==title) renderNavigation(); }
async function movePage(pageId,parentId) { const page=pageById(pageId); if(parentId===pageId||descendants(pageId).some(child=>child.id===parentId)) return alert("A page cannot be moved into itself or one of its children."); checkpoint(); await commit("page.move",{pageId,parentId},()=>{page.parentId=parentId;page.updatedAt=now();}); render(); }
async function reorderPage(pageId,delta) { const page=pageById(pageId), siblings=childrenOf(page.parentId),at=siblings.findIndex(item=>item.id===pageId),to=at+delta;if(to<0||to>=siblings.length)return; const before=delta<0?siblings[to].id:(siblings[to+1]?.id??null); checkpoint(); await commit("page.reorder",{pageId,beforePageId:before},()=>{const all=workspace().pages,from=all.indexOf(page),target=before?all.indexOf(pageById(before)):all.length;all.splice(from,1);all.splice(target>from?target-1:target,0,page);});renderNavigation(); }
async function setFavourite(page,value){await commit("page.set-favourite",{pageId:page.id,favourite:value},()=>{page.favourite=value;});renderNavigation();}
async function trash(page){if(!requireResolvedEdit("moving content to Trash"))return false;checkpoint();await commit("page.trash",{pageId:page.id},()=>{const stamp=now();for(const target of [page,...descendants(page.id)])target.deletedAt=stamp;});if(state.activePageId===page.id)state.activePageId=visiblePages()[0]?.id??null;render();return true;}
async function restore(page){checkpoint();await commit("page.restore",{pageId:page.id},()=>{const targets=new Set([page]);let changed=true;while(changed){changed=false;for(const candidate of workspace().pages)if(candidate.parentId&&[...targets].some(target=>target.id===candidate.parentId)&&!targets.has(candidate)){targets.add(candidate);changed=true;}}for(let parent=page.parentId?pageById(page.parentId):null;parent;parent=parent.parentId?pageById(parent.parentId):null)targets.add(parent);for(const target of targets)delete target.deletedAt;});openPage(page.id);}

function renderNavigation(){
  const expanded=new Set(state.expandedPageIds), branch=(parentId,depth=0)=>childrenOf(parentId).map(page=>{const kids=childrenOf(page.id),open=expanded.has(page.id);return `<div class="tree-branch"><div class="tree-row ${page.id===state.activePageId?"active":""}" style="--depth:${depth}"><button class="disclosure" data-toggle="${escapeAttribute(page.id)}" aria-label="${open?"Collapse":"Expand"} ${escapeHtml(page.title)}">${kids.length?(open?"⌄":"›"):""}</button><button class="page-link" data-open-page="${escapeAttribute(page.id)}"><span>${databaseForPage(page)?.pageId===page.id?"▦":"□"}</span><span>${escapeHtml(page.title||"Untitled")}</span></button><button class="row-action" data-favourite="${escapeAttribute(page.id)}" aria-label="${page.favourite?"Remove from favourites":"Add to favourites"}">★</button><button class="row-action" data-page-menu="${escapeAttribute(page.id)}" aria-label="Page actions">•••</button></div>${open?`<div>${branch(page.id,depth+1)}</div>`:""}</div>`;}).join("");
  $("#pageTree").innerHTML=childrenOf(null).length?branch(null):`<div class="empty-nav">No pages yet</div>`;
  const favourites=visiblePages().filter(page=>page.favourite&&!page.collectionId);$("#favouritesNav").hidden=!favourites.length;$("#favouritesList").innerHTML=favourites.map(page=>`<button class="favourite-link" data-open-page="${escapeAttribute(page.id)}">★ <span>${escapeHtml(page.title||"Untitled")}</span></button>`).join("");
  const trashed=workspace()?.pages.filter(page=>page.deletedAt)??[];$("#trashList").innerHTML=trashed.length?trashed.map(page=>`<div class="tree-row"><span class="page-link">${escapeHtml(page.title||"Untitled")}</span><button class="row-action always" data-restore-page="${escapeAttribute(page.id)}" aria-label="Restore ${escapeHtml(page.title||"Untitled")}">Restore</button></div>`).join(""):`<div class="empty-nav">Trash is empty</div>`;
}
function render(){
  renderNavigation();const page=activePage();if(!page){$("#breadcrumbs").textContent="Workspace";$("#content").innerHTML=`<div class="empty-state"><div class="empty-icon">◇</div><h1>Your workspace is ready</h1><p>Create a page or table. Everything stays on this device.</p><div class="empty-actions"><button class="primary" data-create="page">New page</button><button data-create="database">New table</button></div></div>`;renderContext(null);return;}
  $("#breadcrumbs").innerHTML=`${navigation.length?`<button data-back aria-label="Go back">←</button>`:""}${ancestors(page).map(item=>`<button data-open-page="${escapeAttribute(item.id)}">${escapeHtml(item.title||"Untitled")}</button>`).join("<span>/</span>")}`;
  const database=databaseForPage(page); if(database?.pageId===page.id){renderDatabase(page,database);tagRecordRows(database);}else renderDocument(page,database);renderContext(page);
}
function pageHeader(page,label){return `<div class="page-kicker"><span>${escapeHtml(label)}</span><span><button class="quiet" data-favourite="${escapeAttribute(page.id)}">${page.favourite?"★ Favourited":"☆ Favourite"}</button><button class="danger-text" data-trash-page="${escapeAttribute(page.id)}">Trash</button></span></div><input id="pageTitle" class="page-title" value="${escapeHtml(page.title)}" aria-label="${label==="Table"?"Database title":"Page title"}" placeholder="Untitled" />`;}
function propertyInput(property,value,attrs=""){
  const common=`data-property="${escapeAttribute(property.id)}" ${attrs} aria-label="${escapeHtml(property.name)}"`;
  if(property.type==="checkbox")return `<input type="checkbox" ${common} ${value?"checked":""}>`;
  if(property.type==="number")return `<input type="number" step="any" value="${escapeAttribute(value??"")}" ${common}>`;
  if(property.type==="date")return `<input type="date" value="${escapeHtml(typeof value==="string"?value.slice(0,10):value?.start?.slice(0,10)??"")}" ${common}>`;
  if(["select","status"].includes(property.type))return `<select ${common}><option value="">—</option>${(property.options??[]).map(option=>`<option value="${escapeAttribute(option.id)}" ${value===option.id?"selected":""}>${escapeHtml(option.name)}</option>`).join("")}</select>`;
  if(property.type==="multi-select")return `<select multiple ${common}>${(property.options??[]).map(option=>`<option value="${escapeAttribute(option.id)}" ${Array.isArray(value)&&value.includes(option.id)?"selected":""}>${escapeHtml(option.name)}</option>`).join("")}</select>`;
  const inputType=property.type==="email"?"email":property.type==="url"?"url":property.type==="phone"?"tel":"text";return `<input type="${inputType}" value="${escapeHtml(value??"")}" ${common}>`;
}
function renderFileBlockContent(block){const attachment=workspace().attachments.find(item=>item.id===block.attachmentId);return attachment?`<div class="block-input file" role="group" aria-label="Attachment ${escapeHtml(attachment.fileName)}"><strong>📎 ${escapeHtml(attachment.fileName)}</strong><small>${escapeHtml(attachment.mediaType)} · ${attachment.byteLength} bytes</small><button data-download-attachment="${escapeAttribute(attachment.id)}">Download</button></div>`:`<div class="block-input file unavailable" role="alert">Attachment unavailable: metadata is missing or corrupt.</div>`;}
function renderBlockContent(block,type){if(block.type==="divider")return `<hr>`;if(isFileBlock(block))return renderFileBlockContent(block);return `<div class="block-input ${type}" contenteditable="true" data-block="${escapeAttribute(block.id)}" data-placeholder="Type text, or [[Page name]]">${escapeHtml(block.text)}</div>`;}
function renderBlocks(page){return (page.blocks??[]).map((block,index)=>{const type=BLOCK_TYPES.includes(block.type)?block.type:"unsupported";return `<div class="block-row ${type}" data-block-id="${escapeAttribute(block.id)}"><div class="block-tools"><button data-move-block="${escapeAttribute(block.id)}:-1" ${index?"":"disabled"}>↑</button><button data-move-block="${escapeAttribute(block.id)}:1" ${index<page.blocks.length-1?"":"disabled"}>↓</button></div>${isFileBlock(block)?`<span class="block-type-label">File</span>`:renderBlockTypeSelect({blockId:block.id,type:block.type,types:BLOCK_TYPES,labels:BLOCK_LABELS})}${block.type==="task"?`<input class="task-check" type="checkbox" data-task="${escapeAttribute(block.id)}" ${block.checked?"checked":""}>`:""}${renderBlockContent(block,type)}<button class="delete-block" data-delete-block="${escapeAttribute(block.id)}" aria-label="Delete block">×</button></div>`;}).join("");}
function renderDocument(page,database){const properties=database?database.properties.filter(property=>property.type!=="title").map(property=>`<label class="record-property"><span>${escapeHtml(property.name)}</span>${propertyInput(property,page.properties?.[property.id])}</label>`).join(""):"";$("#content").innerHTML=`<article class="page">${pageHeader(page,database?`Record in ${database.name}`:"Page")}${database?`<section class="record-properties">${properties||'<p class="muted">No properties yet.</p>'}</section><hr class="record-divider">`:""}<div class="blocks">${renderBlocks(page)}</div><button class="add-block" id="addBlock">+ Add block</button></article>`;}
function compareValues(a,b){if(a==null&&b==null)return 0;if(a==null)return 1;if(b==null)return-1;return typeof a==="string"&&typeof b==="string"?a.localeCompare(b):a<b?-1:a>b?1:0;}
function matches(condition,page){if(!condition)return true;if(condition.kind==="and")return condition.children.every(item=>matches(item,page));if(condition.kind==="or")return condition.children.some(item=>matches(item,page));if(condition.kind==="not")return !matches(condition.child,page);const actual=page.properties?.[condition.propertyId],expected=condition.value,empty=actual==null||actual===""||(Array.isArray(actual)&&!actual.length);return ({equals:()=>JSON.stringify(actual)===JSON.stringify(expected),"not-equals":()=>JSON.stringify(actual)!==JSON.stringify(expected),contains:()=>Array.isArray(actual)?actual.includes(expected):String(actual??"").includes(String(expected??"")),"not-contains":()=>!(Array.isArray(actual)?actual.includes(expected):String(actual??"").includes(String(expected??""))),gt:()=>actual>expected,gte:()=>actual>=expected,lt:()=>actual<expected,lte:()=>actual<=expected,before:()=>actual<expected,after:()=>actual>expected,"is-empty":()=>empty,"is-not-empty":()=>!empty}[condition.operator]??(()=>true))();}
function records(database,view){let records=(database.recordPageIds??[]).map(pageById).filter(page=>page&&!page.deletedAt);if(view.filters)records=records.filter(page=>matches(view.filters,page));return records.map((page,index)=>({page,index})).sort((a,b)=>{for(const sort of view.sorts??[]){const result=compareValues(sort.propertyId===database.properties[0].id?a.page.title:a.page.properties?.[sort.propertyId],sort.propertyId===database.properties[0].id?b.page.title:b.page.properties?.[sort.propertyId]);if(result)return sort.direction==="asc"?result:-result;}return a.index-b.index;}).map(item=>item.page);}
function renderDatabase(page,database){const view=database.views[0],order=(view.propertyOrder??database.properties.map(property=>property.id)).filter(id=>view.visiblePropertyIds.includes(id)),properties=order.map(id=>database.properties.find(property=>property.id===id)).filter(Boolean),items=records(database,view);const headers=properties.map((property,index)=>`<th style="width:${escapeAttribute(view.columnWidths?.[property.id]??(property.type==="title"?280:170))}px"><div class="column-head"><button data-property-menu="${escapeAttribute(property.id)}">${escapeHtml(property.name)} <small>${PROPERTY_LABELS[property.type]}</small></button><span><button data-column-move="${escapeAttribute(property.id)}:-1" ${index?"":"disabled"}>←</button><button data-column-move="${escapeAttribute(property.id)}:1" ${index<properties.length-1?"":"disabled"}>→</button></span></div><input class="column-resize" type="range" min="90" max="480" value="${escapeAttribute(view.columnWidths?.[property.id]??(property.type==="title"?280:170))}" data-column-width="${escapeAttribute(property.id)}" aria-label="Width of ${escapeHtml(property.name)}"></th>`).join("");const rows=items.slice(0,500).map(record=>`<tr>${properties.map(property=>`<td>${property.type==="title"?`<button class="record-link" data-open-page="${escapeAttribute(record.id)}">${escapeHtml(record.title||"Untitled")}</button>`:propertyInput(property,record.properties?.[property.id],`data-record="${escapeAttribute(record.id)}"`)}</td>`).join("")}<td class="row-tools"><button data-trash-page="${escapeAttribute(record.id)}" aria-label="Trash record">×</button></td></tr>`).join("");$("#content").innerHTML=`<article class="page database-page">${pageHeader(page,"Table")}<div class="table-toolbar"><span>${items.length} of ${database.recordPageIds?.length??0} records${items.length>500?" · showing first 500":""}</span><span><button id="filterButton">Filter</button><button id="sortButton">Sort</button><button id="addProperty">+ Property</button></span></div><div id="viewControls"></div><div class="table-wrap"><table><thead><tr>${headers}<th class="row-tools"></th></tr></thead><tbody>${rows}</tbody></table>${rows?"":'<div class="table-empty">No records match this view.</div>'}</div><button class="add-row" id="addRecord">+ New record</button></article>`;}
function renderContext(page){if(!page){$("#outgoingLinks").innerHTML=$("#backlinks").innerHTML='<p class="muted">Open a page to see connections.</p>';return;}rebuildLinks();const outgoing=workspace().linkIndex.filter(link=>link.sourcePageId===page.id).map(link=>pageById(link.targetPageId)).filter(Boolean),incoming=workspace().linkIndex.filter(link=>link.targetPageId===page.id).map(link=>pageById(link.sourcePageId)).filter(Boolean);const html=(items,empty)=>items.length?[...new Map(items.map(item=>[item.id,item])).values()].map(item=>`<button class="context-link" data-open-page="${escapeAttribute(item.id)}">↗ ${escapeHtml(item.title)}</button>`).join(""):`<p class="muted">${empty}</p>`;$("#outgoingLinks").innerHTML=html(outgoing,"No links from this page.");$("#backlinks").innerHTML=html(incoming,"No backlinks yet.");$("#attachments").innerHTML='<p class="muted">Attachments remain available through native backup/export.</p>';}

async function updateRecord(record,property,value){const database=databaseForPage(record);await commit("database.record-update",{pageId:record.id,values:{[property.id]:value}},()=>{record.properties??={};if(value===undefined)delete record.properties[property.id];else record.properties[property.id]=value;});}
function readProperty(target,property){if(property.type==="checkbox")return target.checked;if(property.type==="number")return target.value===""?undefined:Number(target.value);if(property.type==="multi-select")return [...target.selectedOptions].map(option=>option.value);return target.value||undefined;}


function showPageMenu(page){const choices=visiblePages().filter(candidate=>candidate.id!==page.id&&!descendants(page.id).some(child=>child.id===candidate.id));const menu=`<div class="inline-panel"><strong>Page actions</strong><label>Move inside<select id="moveParent"><option value="">Workspace root</option>${choices.map(item=>`<option value="${escapeAttribute(item.id)}" ${page.parentId===item.id?"selected":""}>${escapeHtml(item.title)}</option>`).join("")}</select></label><button data-confirm-move="${escapeAttribute(page.id)}">Move page</button><button data-move-page="${escapeAttribute(page.id)}:-1" aria-label="Move ${escapeHtml(page.title)} up">↑ Up</button><button data-move-page="${escapeAttribute(page.id)}:1" aria-label="Move ${escapeHtml(page.title)} down">↓ Down</button><button data-add-child="${escapeAttribute(page.id)}">Add child page</button><button data-add-database="${escapeAttribute(page.id)}">Add table</button></div>`;$("#content").insertAdjacentHTML("afterbegin",menu);}
function showPropertyMenu(database,property){const options=(property.options??[]).map(option=>option.name).join(", "),visible=database.views[0].visiblePropertyIds.includes(property.id);$("#viewControls").innerHTML=`<div class="inline-panel property-panel"><label>Name<input id="propertyName" value="${escapeHtml(property.name)}"></label>${property.type==="title"?"":`<label>Type<select id="propertyType">${PROPERTY_TYPES.map(type=>`<option value="${type}" ${type===property.type?"selected":""}>${PROPERTY_LABELS[type]}</option>`).join("")}</select></label>`}<label class="option-definition" ${["select","multi-select","status"].includes(property.type)?"":"hidden"}>Options (comma separated)<input id="propertyOptions" value="${escapeHtml(options)}"></label><label>Visible in table<input id="propertyVisible" type="checkbox" ${visible?"checked":""}></label><button data-save-property="${escapeAttribute(property.id)}">Save</button>${property.type==="title"?"":`<button class="danger-text" data-delete-property="${escapeAttribute(property.id)}">Delete property</button>`}</div>`;}
const FILTER_OPERATORS=["equals","not-equals","contains","not-contains","gt","gte","lt","lte","before","after","is-empty","is-not-empty"];
function filterRow(database,condition,index){return `<div class="filter-clause" data-filter-index="${index}"><select id="${index?"": "filterProperty"}" data-filter-property>${database.properties.map(property=>`<option value="${escapeAttribute(property.id)}" ${condition?.propertyId===property.id?"selected":""}>${escapeHtml(property.name)}</option>`).join("")}</select><select id="${index?"":"filterOperator"}" data-filter-operator>${FILTER_OPERATORS.map(operator=>`<option value="${operator}" ${condition?.operator===operator?"selected":""}>${operator.replaceAll("-"," ")}</option>`).join("")}</select><input id="${index?"":"filterValue"}" data-filter-value value="${escapeHtml(condition?.value??"")}" placeholder="Value"><button data-remove-filter="${index}" aria-label="Remove filter">×</button></div>`;}
function showFilter(database){const view=database.views[0],negated=view.filters?.kind==="not",root=negated?view.filters.child:view.filters,kind=root?.kind==="or"?"or":"and",conditions=root?.kind==="and"||root?.kind==="or"?root.children:root?.kind==="condition"?[root]:[];$("#viewControls").innerHTML=`<div class="inline-panel"><label>Match<select id="filterKind"><option value="and" ${kind==="and"?"selected":""}>all (AND)</option><option value="or" ${kind==="or"?"selected":""}>any (OR)</option></select></label><label>Negate group<input id="filterNot" type="checkbox" ${negated?"checked":""}></label><div id="filterClauses">${(conditions.length?conditions:[null]).map((condition,index)=>filterRow(database,condition,index)).join("")}</div><button id="addFilterClause">+ Condition</button><button id="applyFilter">Apply</button><button id="clearFilter">Clear</button></div>`;}
function showSort(database){const view=database.views[0],sorts=view.sorts??[];$("#viewControls").innerHTML=`<div class="inline-panel"><strong>Sort clauses</strong><div id="sortClauses">${sorts.map((sort,index)=>sortRow(database,sort,index)).join("")||sortRow(database,{propertyId:database.properties[0].id,direction:"asc"},0)}</div><button id="addSortClause">+ Clause</button><button id="applySort">Apply sorts</button><button id="clearSort">Clear</button></div>`;}
function sortRow(database,sort,index){return `<div class="sort-clause" data-sort-index="${index}"><select data-sort-property>${database.properties.map(property=>`<option value="${escapeAttribute(property.id)}" ${property.id===sort.propertyId?"selected":""}>${escapeHtml(property.name)}</option>`).join("")}</select><select data-sort-direction><option value="asc" ${sort.direction==="asc"?"selected":""}>Ascending</option><option value="desc" ${sort.direction==="desc"?"selected":""}>Descending</option></select><button data-remove-sort="${index}">×</button></div>`;}
async function updateView(database,patch){await commit("database.view-update",{databaseId:database.id,viewId:database.views[0].id,patch},()=>Object.assign(database.views[0],patch));render();}

document.addEventListener("click",async event=>{const button=event.target.closest("button");if(!button)return;try{
  if(button.id==="retryEdit")return retryPendingEdit();
  if(button.id==="discardEdit")return discardPendingEdit();if(button.dataset.downloadAttachment){const result=await adapter.readAttachment(button.dataset.downloadAttachment),blob=new Blob([result.bytes],{type:result.attachment.mediaType}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=result.attachment.fileName;link.click();URL.revokeObjectURL(url);return;}
  if(button.dataset.searchRetry!==undefined)return renderSearch($("#searchInput").value);
  if(button.dataset.searchEntityId){const hit=currentSearchHits.get(button.dataset.searchEntityId);if(hit)return activateSearchHit(hit);}
  if(button.id==="openSearch"){$("#searchDialog").showModal();$("#searchInput").value="";renderSearchStatus(searchStatus("","idle"));$("#searchInput").focus();return;}
  if(button.id==="openSidebar")return $("#sidebar").classList.add("open");if(button.id==="closeSidebar")return $("#sidebar").classList.remove("open");
  if(editRecovery.snapshot().blocked){if(button.dataset.openPage||button.hasAttribute("data-back"))return requireResolvedEdit("leaving this page");if(button.dataset.trashPage||button.dataset.deleteBlock||button.dataset.deleteProperty)return requireResolvedEdit("moving content to Trash");if(button.id==="exportWorkspace")return exportWorkspace();if(button.id==="createVerifiedBackup")return createVerifiedBackup();if(button.id==="restoreWorkspace"||button.id==="restoreVerifiedBackup")return requireResolvedEdit("restoring");return requireResolvedEdit("continuing");}
  if(button.dataset.openPage){const blockId=button.dataset.focusBlock;setContextOpen(false,false);if(openPage(button.dataset.openPage)&&blockId)requestAnimationFrame(()=>findByDataValue("[data-block-id]","blockId",blockId)?.querySelector("[data-block]")?.focus());return;}
  if(button.hasAttribute("data-back"))return openPage(navigation.pop(),false);
  if(button.dataset.create)return createPage(null,button.dataset.create==="database");
  if(button.id==="addRootPage")return createPage();
  if(button.id==="addRootDatabase")return createPage(null,true);
  if(button.dataset.toggle){const set=new Set(state.expandedPageIds);set.has(button.dataset.toggle)?set.delete(button.dataset.toggle):set.add(button.dataset.toggle);state.expandedPageIds=[...set];await saveUi();return renderNavigation();}
  if(button.dataset.favourite)return setFavourite(pageById(button.dataset.favourite),!pageById(button.dataset.favourite).favourite);
  if(button.dataset.pageMenu)return showPageMenu(pageById(button.dataset.pageMenu));
  if(button.dataset.confirmMove)return movePage(button.dataset.confirmMove,$("#moveParent").value||null);
  if(button.dataset.addChild)return createPage(button.dataset.addChild);
  if(button.dataset.addDatabase)return createPage(button.dataset.addDatabase,true);
  if(button.dataset.restorePage)return restore(pageById(button.dataset.restorePage));
  if(button.dataset.trashPage&&confirm("Move this page to Trash?"))return trash(pageById(button.dataset.trashPage));
  if(button.dataset.movePage){const[id,delta]=delegatedIdAndDelta(button.dataset.movePage);return reorderPage(id,delta);}
  const page=activePage(),database=databaseForPage(page);
  if(button.id==="addBlock"){checkpoint();const block={id:uid(),type:"paragraph",text:"",children:[]};await commit("block.create",{pageId:page.id,position:{parentBlockId:null,beforeBlockId:null},block},()=>page.blocks.push(block));return render();}
  if(button.dataset.deleteBlock){checkpoint();const blockId=button.dataset.deleteBlock;await commit("block.delete",{pageId:page.id,blockId},()=>{page.blocks=page.blocks.filter(block=>block.id!==blockId);});return render();}
  if(button.dataset.moveBlock){checkpoint();const[id,delta]=delegatedIdAndDelta(button.dataset.moveBlock),at=page.blocks.findIndex(block=>block.id===id),to=at+delta;if(to<0||to>=page.blocks.length)return;const beforeBlockId=delta<0?page.blocks[to].id:(page.blocks[to+1]?.id??null);await commit("block.move",{pageId:page.id,blockId:id,target:{pageId:page.id,parentBlockId:null,beforeBlockId}},()=>{[page.blocks[at],page.blocks[to]]=[page.blocks[to],page.blocks[at]];});return render();}
  if(button.id==="addRecord"){await commit("database.record-create",{databaseId:database.id,title:"Untitled",values:{}},()=>{const record={id:uid(),parentId:database.pageId,title:"Untitled",blocks:[],createdAt:now(),updatedAt:now(),collectionId:database.id,properties:{}};workspace().pages.push(record);database.recordPageIds.push(record.id);});return render();}
  if(button.id==="addProperty"){const name=prompt("Property name","Property");if(!name)return;await commit("database.property-add",{databaseId:database.id,property:{name,type:"text"}},()=>{const property={id:uid(),name,type:"text"};database.properties.push(property);database.views[0].visiblePropertyIds.push(property.id);database.views[0].propertyOrder.push(property.id);});return render();}
  if(button.dataset.propertyMenu)return showPropertyMenu(database,database.properties.find(property=>property.id===button.dataset.propertyMenu));
  if(button.dataset.saveProperty){const property=database.properties.find(item=>item.id===button.dataset.saveProperty),type=$("#propertyType")?.value??"title",names=($("#propertyOptions")?.value??"").split(",").map(name=>name.trim()).filter(Boolean),options=names.map(name=>property.options?.find(option=>option.name===name)??{id:uid(),name}),visible=$("#propertyVisible").checked;await commit("database.property-update",{databaseId:database.id,propertyId:property.id,patch:{name:$("#propertyName").value,type,options:["select","multi-select","status"].includes(type)?options:undefined}},()=>Object.assign(property,{name:$("#propertyName").value,type,options:["select","multi-select","status"].includes(type)?options:undefined}));const ids=new Set(database.views[0].visiblePropertyIds);visible?ids.add(property.id):ids.delete(property.id);await updateView(database,{visiblePropertyIds:[...ids]});return;}
  if(button.dataset.deleteProperty&&confirm("Delete this property and its values?")){await commit("database.property-delete",{databaseId:database.id,propertyId:button.dataset.deleteProperty},()=>{database.properties=database.properties.filter(property=>property.id!==button.dataset.deleteProperty);for(const record of database.recordPageIds.map(pageById))delete record.properties?.[button.dataset.deleteProperty];});return render();}
  if(button.dataset.columnMove){const[id,delta]=delegatedIdAndDelta(button.dataset.columnMove),order=[...database.views[0].propertyOrder],at=order.indexOf(id),to=at+delta;if(to>=0&&to<order.length)[order[at],order[to]]=[order[to],order[at]];return updateView(database,{propertyOrder:order});}
  if(button.id==="filterButton")return showFilter(database);if(button.id==="sortButton")return showSort(database);
  if(button.id==="addFilterClause"){$("#filterClauses").insertAdjacentHTML("beforeend",filterRow(database,null,$("#filterClauses").children.length));return;}
  if(button.dataset.removeFilter!==undefined){button.closest(".filter-clause").remove();return;}
  if(button.id==="applyFilter"){const conditions=[...document.querySelectorAll(".filter-clause")].map(row=>{const property=database.properties.find(item=>item.id===row.querySelector("[data-filter-property]").value),operator=row.querySelector("[data-filter-operator]").value,raw=row.querySelector("[data-filter-value]").value,value=property.type==="number"?Number(raw):property.type==="checkbox"?raw==="true":raw;return{kind:"condition",propertyId:property.id,operator,...(!["is-empty","is-not-empty"].includes(operator)?{value}:{})};}),group=conditions.length===1?conditions[0]:{kind:$("#filterKind").value,children:conditions},filters=$("#filterNot").checked?{kind:"not",child:group}:group;return updateView(database,{filters});}
  if(button.id==="clearFilter")return updateView(database,{filters:undefined});
  if(button.id==="addSortClause"){$("#sortClauses").insertAdjacentHTML("beforeend",sortRow(database,{propertyId:database.properties[0].id,direction:"asc"},$("#sortClauses").children.length));return;}
  if(button.dataset.removeSort!==undefined){button.closest(".sort-clause").remove();return;}
  if(button.id==="applySort"){const sorts=[...document.querySelectorAll(".sort-clause")].map(row=>({propertyId:row.querySelector("[data-sort-property]").value,direction:row.querySelector("[data-sort-direction]").value}));return updateView(database,{sorts});}
  if(button.id==="clearSort")return updateView(database,{sorts:[]});
  if(button.id==="exportWorkspace")return exportWorkspace();
  if(button.id==="restoreWorkspace"){if(requireResolvedEdit("restoring"))$("#restoreFile").click();return;}
  if(button.id==="attachFile"){if(requireResolvedEdit("attaching a file"))return $("#attachmentFile").click();return;}
  if(button.id==="createVerifiedBackup")return createVerifiedBackup();
  if(button.id==="restoreVerifiedBackup"){if(requireResolvedEdit("restoring"))$("#verifiedBackupFile").click();return;}
}catch(error){console.error(error);}});

$("#restoreFile").addEventListener("change",async event=>{const[file]=event.target.files;event.target.value="";if(file)try{await restoreWorkspace(file);}catch(error){alert(error.message);}});
$("#attachmentFile").addEventListener("change",async event=>{const files=event.target.files;event.target.value="";try{await attachmentIngestion.fromSelection(files);}catch{ /* explicit status is rendered by the shared ingestion boundary */ }});
$("#verifiedBackupFile").addEventListener("change",async event=>{const[file]=event.target.files;event.target.value="";if(file)try{await restoreVerifiedBackup(file);}catch(error){alert(error.message);}});$("#content").addEventListener("dragover",event=>{if(adapter.kind==="tauri"&&event.dataTransfer?.types?.includes("Files"))event.preventDefault();});$("#content").addEventListener("drop",async event=>{if(adapter.kind!=="tauri")return;try{await attachmentIngestion.fromDrop(event);}catch{ /* explicit status is rendered by the shared ingestion boundary */ }});

document.addEventListener("input",event=>{const target=event.target,page=activePage();if(target.id==="searchInput"){void renderSearch(target.value);return;}if(!page)return;
  if(target.id==="pageTitle"){const descriptor={kind:"page-title",pageId:page.id};queueCanonicalEdit({key:`page:title:${page.id}`,label:"Page title",candidate:{type:"page.rename",payload:{pageId:page.id,title:target.value}},target:descriptor,rerender:true});return;}
  if(target.dataset.block){const blockId=target.dataset.block,block=page.blocks.find(item=>item.id===blockId),draft=structuredClone(block);draft.text=target.textContent;refreshReferences(draft);queueCanonicalEdit({key:`block:text:${page.id}:${blockId}`,label:`${BLOCK_LABELS[block?.type]??"Block"} text`,candidate:{type:"block.update-content",payload:{pageId:page.id,blockId,content:{text:draft.text,references:draft.references??[]}}},target:{kind:"block-text",pageId:page.id,blockId}});return;}
  if(target.dataset.columnWidth){const database=databaseForPage(page),propertyId=target.dataset.columnWidth,widths={...database.views[0].columnWidths,[propertyId]:Number(target.value)};queueCanonicalEdit({key:`view:width:${database.views[0].id}:${propertyId}`,label:"Table column width",candidate:{type:"database.view-update",payload:{databaseId:database.id,viewId:database.views[0].id,patch:{columnWidths:widths}}},target:{kind:"view-width",pageId:page.id,propertyId}});}
});
document.addEventListener("change",event=>{const target=event.target,page=activePage();if(!page)return;const database=databaseForPage(page);
  if(target.dataset.property){const record=target.dataset.record?pageById(target.dataset.record):page,property=database.properties.find(item=>item.id===target.dataset.property),value=readProperty(target,property);queueCanonicalEdit({key:`record:property:${record.id}:${property.id}`,label:`${property.name} property`,candidate:{type:"database.record-update",payload:{pageId:record.id,values:{[property.id]:value}}},target:{kind:"record-property",pageId:record.id,propertyId:property.id},rerender:false});return;}
  if(target.dataset.blockType){const blockId=target.dataset.blockType,transform={type:target.value,...(target.value==="task"?{checked:false}:{})};queueCanonicalEdit({key:`block:type:${page.id}:${blockId}`,label:"Block type",candidate:{type:"block.transform",payload:{pageId:page.id,blockId,transform}},target:{kind:"block-type",pageId:page.id,blockId},rerender:true});return;}
  if(target.dataset.task){const blockId=target.dataset.task;queueCanonicalEdit({key:`block:task:${page.id}:${blockId}`,label:"Task state",candidate:{type:"block.transform",payload:{pageId:page.id,blockId,transform:{type:"task",checked:target.checked}}},target:{kind:"task",pageId:page.id,blockId}});}
});
document.addEventListener("paste",event=>{const input=event.target.closest?.("[data-block]");if(!input)return;const text=event.clipboardData?.getData("text/plain")??"";if(!/[\r\n]/.test(text))return;if(!requireResolvedEdit("pasting")){event.preventDefault();return;}const page=activePage(),blockId=input.dataset.block,{prefix,suffix}=selectionTextParts(input);event.preventDefault();let commands;try{commands=multilinePasteCommands({pageId:page.id,blocks:page.blocks,activeBlockId:blockId,text,prefix,suffix,createId:uid,resolveReferences:referencesForText});}catch(error){$("#saveState").textContent=error instanceof Error?error.message:"Multiline paste could not be applied.";return;}checkpoint();queueCanonicalEdit({key:`block:paste:${page.id}:${blockId}`,label:"Multiline paste",candidate:{type:"block.batch",payload:{commands}},target:{kind:"block-text",pageId:page.id,blockId},rerender:true});});
document.addEventListener("focusin",event=>{if(event.target.id==="pageTitle"||event.target.dataset?.block)checkpoint();});
document.addEventListener("focusout",event=>{if((event.target.id==="pageTitle"||event.target.dataset?.block)&&editRecovery.snapshot().status==="editing"){clearTimeout(editTimer);editTimer=null;void editRecovery.commit();}});
document.addEventListener("keydown",event=>{const mod=event.ctrlKey||event.metaKey;if(mod&&event.key.toLowerCase()==="k"){event.preventDefault();$("#openSearch").click();return;}if(mod&&event.key.toLowerCase()==="z"){event.preventDefault();if(!requireResolvedEdit("undoing"))return;if(adapter.kind==="tauri"){$("#saveState").textContent="Native undo requires typed command support and was not applied.";return;}const stack=event.shiftKey?future:history,other=event.shiftKey?history:future;if(stack.length){other.push(snapshot());state=migrateLoaded(JSON.parse(stack.pop()));void saveLocal();render();}return;}const input=event.target.closest?.("[data-block]");if(!input)return;const page=activePage(),at=page.blocks.findIndex(block=>block.id===input.dataset.block),block=page.blocks[at];if((event.key==="Enter"&&!event.shiftKey)||(mod&&event.key.toLowerCase()==="d")||(event.altKey&&["ArrowUp","ArrowDown"].includes(event.key))){if(!requireResolvedEdit("continuing")){event.preventDefault();return;}}if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();checkpoint();const next={id:uid(),type:block.type==="divider"?"paragraph":block.type,text:"",children:[]},beforeBlockId=page.blocks[at+1]?.id??null;void commit("block.create",{pageId:page.id,position:{parentBlockId:null,beforeBlockId},block:next},()=>page.blocks.splice(at+1,0,next)).then(()=>{render();requestAnimationFrame(()=>document.querySelector(`[data-block="${next.id}"]`)?.focus());});}if(mod&&event.key.toLowerCase()==="d"){event.preventDefault();checkpoint();const newBlockId=uid();void commit("block.duplicate",{pageId:page.id,blockId:block.id,newBlockId},()=>{const copy=structuredClone(block);copy.id=newBlockId;page.blocks.splice(at+1,0,copy);}).then(render);}if(event.altKey&&["ArrowUp","ArrowDown"].includes(event.key)){event.preventDefault();findByDataValue("[data-move-block]","moveBlock",`${block.id}:${event.key==="ArrowUp"?-1:1}`)?.click();}});
async function renderSearch(query){
  const term=String(query??"").trim(),request=++searchRequest;
  if(!term){currentSearchHits=new Map();renderSearchStatus(searchStatus(term,"idle"));return;}
  renderSearchStatus(searchStatus(term,"loading"));
  try{
    const raw=adapter.kind==="tauri"?await adapter.search(term,50):buildBrowserSearchHits(workspace(),term,50);
    if(request!==searchRequest)return;
    const hits=normalizeSearchHits(raw??[],50);currentSearchHits=new Map(hits.map(hit=>[hit.entityId,hit]));
    if(!hits.length){renderSearchStatus(searchStatus(term,"empty"));return;}
    const results=$("#searchResults");results.replaceChildren();
    for(const hit of hits){const button=document.createElement("button"),icon=document.createElement("span"),copy=document.createElement("span"),title=document.createElement("strong"),snippet=document.createElement("small");button.type="button";button.dataset.searchEntityId=hit.entityId;icon.className="result-icon";icon.setAttribute("aria-hidden","true");icon.textContent=hit.entityType==="row"?"▦":"□";title.textContent=hit.title;snippet.textContent=hit.snippet;copy.append(title,snippet);button.append(icon,copy);results.append(button);}
  }catch{if(request===searchRequest){currentSearchHits=new Map();renderSearchStatus(searchStatus(term,"error"));}}
}
function renderSearchStatus(status){const results=$("#searchResults"),message=document.createElement("div");message.className=`search-hint search-${status.kind}`;message.textContent=status.message;results.replaceChildren(message);if(status.kind==="error"){const retry=document.createElement("button");retry.type="button";retry.dataset.searchRetry="";retry.textContent="Retry search";results.append(retry);}}
function activateSearchHit(hit){const target=resolveSearchTarget(hit,workspace());if(!target)return;const opened=openPage(target.pageId);if(!opened)return;$("#searchDialog").close();requestAnimationFrame(()=>{if(target.blockId){findByDataValue("[data-block-id]","blockId",target.blockId)?.querySelector("[data-block]")?.focus();return;}if(target.recordId===target.pageId){$("#pageTitle")?.focus();return;}const row=findByDataValue("[data-record-id]","recordId",target.recordId);row?.querySelector("input,select,button")?.focus();});}

import { buildLinkEntries, linkEntryLabel } from "./link-presentation.js";
function findByDataValue(selector,key,value){return [...document.querySelectorAll(selector)].find(element=>element.dataset[key]===value);}
function setContextOpen(open,returnFocus=true){const panel=$("#contextPanel"),toggle=$("#openContext");panel.classList.toggle("open",open);toggle.setAttribute("aria-expanded",String(open));if(open)requestAnimationFrame(()=>$("#contextPanelTitle").focus());else if(returnFocus)toggle.focus();}
document.addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;if(button.id==="openContext"){setContextOpen(true);return;}if(button.id==="closeContext"){setContextOpen(false);return;}if(!button.dataset.revealTrashed)return;const restore=findByDataValue("[data-restore-page]","restorePage",button.dataset.revealTrashed);setContextOpen(false,false);$("#sidebar").classList.add("open");restore?.scrollIntoView({block:"nearest"});restore?.focus();});
document.addEventListener("keydown",event=>{if(event.key==="Escape"&&$("#contextPanel").classList.contains("open")){event.preventDefault();setContextOpen(false);}});
function renderLinkLifecycle(container,entries,emptyText,includeBlockTarget=false){container.replaceChildren();if(!entries.length){const empty=document.createElement("p");empty.className="muted";empty.textContent=emptyText;container.append(empty);return;}for(const entry of entries){const available=entry.status==="live",recoverable=entry.status==="trashed",control=document.createElement(available||recoverable?"button":"span");control.className=`context-link${available?"":recoverable?" recovery":" unavailable"}`;control.textContent=linkEntryLabel(entry);if(available){control.type="button";control.dataset.openPage=entry.pageId;if(includeBlockTarget)control.dataset.focusBlock=entry.blockId;}else if(recoverable){control.type="button";control.dataset.revealTrashed=entry.pageId;}else control.setAttribute("aria-disabled","true");container.append(control);}}
renderContext=function(page){if(!page){renderLinkLifecycle($("#outgoingLinks"),[],"Open a page to see connections.");renderLinkLifecycle($("#backlinks"),[],"Open a page to see connections.");return;}rebuildLinks();const input={pages:workspace().pages,links:workspace().linkIndex,pageId:page.id};renderLinkLifecycle($("#outgoingLinks"),buildLinkEntries({...input,direction:"outgoing"}),"No links from this page.");renderLinkLifecycle($("#backlinks"),buildLinkEntries({...input,direction:"incoming"}),"No backlinks yet.",true);const attachments=$("#attachments"),message=document.createElement("p");message.className="muted";message.textContent="Attachments remain available through native backup/export.";attachments.replaceChildren(message);};
function renderCopyableInternalUrls(page){const pageButton=$("#copyPageLink"),backlinks=$("#backlinks");if(!page){pageButton.hidden=true;delete pageButton.dataset.copyInternalUrl;return;}pageButton.hidden=false;pageButton.dataset.copyInternalUrl=buildInternalUrl({workspaceId:workspace().id,pageId:page.id});for(const button of backlinks.querySelectorAll("button[data-focus-block]")){const copy=document.createElement("button");copy.type="button";copy.className="quiet";copy.textContent="Copy block link";copy.dataset.copyInternalUrl=buildInternalUrl({workspaceId:workspace().id,pageId:button.dataset.openPage,blockId:button.dataset.focusBlock});copy.setAttribute("aria-label",`Copy internal block link from ${button.textContent}`);button.after(copy);}}
const renderLinkContext=renderContext;renderContext=function(page){renderLinkContext(page);renderCopyableInternalUrls(page);};
document.addEventListener("click",async event=>{const button=event.target.closest("button");if(!button?.dataset.copyInternalUrl)return;const url=button.dataset.copyInternalUrl;try{await navigator.clipboard.writeText(url);$("#saveState").textContent="Internal link copied";}catch{$("#saveState").textContent="Internal link could not be copied";}});

$("#saveState").textContent=adapter.kind==="tauri"?"Connected to Motion":"Browser development mode";
for(const id of ["attachFile","createVerifiedBackup","restoreVerifiedBackup"]){const button=$(`#${id}`);button.disabled=adapter.kind!=="tauri";if(button.disabled)button.title="Available in the native Motion application";}
function tagRecordRows(database){const items=records(database,database.views[0]).slice(0,500);[...$("#content").querySelectorAll("tbody tr")].forEach((row,index)=>{row.dataset.recordId=items[index].id;});}
render();
