import { formulaError, isFormulaError, type Expression, type FormulaValue, type ParsedFormula } from "./types.js";
export interface EvaluationContext { readonly properties: Readonly<Record<string, FormulaValue>> }
const truthy = (v: FormulaValue): boolean => v !== null && v !== false && v !== 0 && v !== "";
const comparable = (v: FormulaValue): string|number|boolean|null => v instanceof Date ? v.getTime() : v as string|number|boolean|null;
export function evaluate(formula: ParsedFormula | Expression, context: EvaluationContext): FormulaValue {
  const node = "expression" in formula ? formula.expression : formula;
  const run = (n: Expression): FormulaValue => {
    if (n.kind === "literal") return n.value instanceof Date ? new Date(n.value.getTime()) : n.value;
    if (n.kind === "property") return Object.prototype.hasOwnProperty.call(context.properties,n.name) ? context.properties[n.name]! : formulaError("NAME",`Unknown property '${n.name}'`);
    if (n.kind === "unary") { const v=run(n.operand); if(isFormulaError(v)) return v; if(n.operator==="not") return !truthy(v); if(typeof v!=="number") return formulaError("TYPE",`${n.operator} requires a number`); return n.operator==="-"?-v:v; }
    if (n.kind === "binary") { const l=run(n.left); if(isFormulaError(l)) return l; if(n.operator==="and"&&!truthy(l)) return false; if(n.operator==="or"&&truthy(l)) return true; const r=run(n.right); if(isFormulaError(r)) return r; if(n.operator==="and") return truthy(r); if(n.operator==="or") return truthy(r); if(["=","!=","<","<=",">",">="].includes(n.operator)) { const a=comparable(l),b=comparable(r); if (typeof a!==typeof b && a!==null && b!==null) return formulaError("TYPE","Cannot compare different types"); if(n.operator==="=") return a===b; if(n.operator==="!=") return a!==b; if(a===null||b===null) return false; if(n.operator==="<") return a<b; if(n.operator==="<=") return a<=b; if(n.operator===">") return a>b; return a>=b; }
      if(n.operator==="+"&&(typeof l==="string"||typeof r==="string")) return `${l ?? ""}${r ?? ""}`; if(typeof l!=="number"||typeof r!=="number") return formulaError("TYPE",`${n.operator} requires numbers`); if((n.operator==="/"||n.operator==="%")&&r===0) return formulaError("DIV_ZERO","Division by zero"); return n.operator==="+"?l+r:n.operator==="-"?l-r:n.operator==="*"?l*r:n.operator==="/"?l/r:l%r;
    }
    const args=n.arguments.map(run); const error=args.find(isFormulaError); if(error) return error; const arity=(count:number)=>args.length===count ? null : formulaError("TYPE",`${n.name} expects ${count} arguments`); const required=(count:number)=>arity(count);
    switch(n.name){ case "IF": {const e=required(3); return e??(truthy(args[0]!)?args[1]!:args[2]!);} case "CONCAT": return args.map(v=>v===null?"":v instanceof Date?v.toISOString():String(v)).join(""); case "LOWER": case "UPPER": {const e=required(1); if(e)return e; if(typeof args[0]!=="string")return formulaError("TYPE",`${n.name} expects text`); return n.name==="LOWER"?args[0].toLowerCase():args[0].toUpperCase();} case "DATE": {const e=required(1); if(e)return e; if(typeof args[0]!=="string")return formulaError("TYPE","DATE expects ISO text"); const d=new Date(args[0]); return Number.isNaN(d.getTime())?formulaError("TYPE","Invalid date"):d;} case "YEAR": {const e=required(1); if(e)return e; return args[0] instanceof Date?args[0].getUTCFullYear():formulaError("TYPE","YEAR expects a date");} case "DAYS_BETWEEN": {const e=required(2); if(e)return e; return args[0] instanceof Date&&args[1] instanceof Date?Math.trunc((args[0].getTime()-args[1].getTime())/86400000):formulaError("TYPE","DAYS_BETWEEN expects dates");} case "EMPTY": {const e=required(1); return e??(args[0]===null||args[0]==="");} default:return formulaError("NAME",`Unknown function '${n.name}'`); }
  }; return run(node);
}
